name: relion-5.1
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - setuptools
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.1+cu128
      - tqdm
      - mrcfile
      - starfile
      - loguru
      - scikit-learn
      - umap-learn
      - matplotlib
      - morphosamplers
      - pydantic
      - napari[all]
      - tsnecuda
      - PyQt5
      - typer
      - click
      - biopython
      - fastcluster
      - seaborn
      - dill
      - numpy
      - scipy
      - skan
      - opencv-python
      - git+https://github.com/3dem/relion-classranker
      - git+https://github.com/3dem/relion-blush
      - git+https://github.com/3dem/DynaMight
      - git+https://github.com/3dem/topaz
      - git+https://github.com/3dem/model-angelo
      - git+https://github.com/teamtomo/torch-fourier-rescale
      - -e ".[vis]"
