name: relion-5.0
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - setuptools
  - pip:
      - torch
      - torchvision
      - tqdm
      - mrcfile
      - starfile
      - loguru
      - scikit-learn
      - umap-learn
      - matplotlib
      - morphosamplers
      - pydantic
      - napari[all]
      - tsnecuda
      - typer
      - click
      - biopython
      - fastcluster
      - seaborn
      - dill
      - numpy
      - scipy
      - git+https://github.com/3dem/relion-classranker
      - git+https://github.com/3dem/relion-blush
      - git+https://github.com/3dem/DynaMight
      - git+https://github.com/3dem/topaz
      - git+https://github.com/3dem/model-angelo
      - git+https://github.com/teamtomo/torch-fourier-rescale
      - -e ".[vis]"
